"""add user role

Revision ID: 43617d9b6cfe
Revises: 9c6bf50e72cc
Create Date: 2026-07-30 01:02:50.726803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43617d9b6cfe'
down_revision: Union[str, Sequence[str], None] = '9c6bf50e72cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=30), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
